export const CHANGE_WRITER_INFO = 'writer/CHANGE_WRITER_INFO';
export const CHANGE_WRITER_DETAIL_ATTENTION = 'writer/CHANGE_WRITER_DETAIL_ATTENTION';
export const ADD_WRITER_LIST = 'writer/ADD_WRITER_LIST';
